apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ondrej-helm-from-git2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ondrej
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    # targetRevision: master
    path: charts/one-image
    helm:
      releaseName: git2
      valuesObject:
        host: hello-ondrej.k8s.sikademo.com
        image: ondrejsika/iceland-2
