apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bar
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  syncWindows:
  - applications:
    - '*'
    duration: 1m
    kind: allow
    schedule: 2 * * * *
    timeZone: UTC
    manualSync: true
