apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ondrej-manifests
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ondrej
  source:
    path: examples/manifests
    repoURL: https://gitlab.sikademo.com/training/ondrej.git
